# Generated by Django 5.0.3 on 2024-03-14 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_item_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='seller',
            field=models.CharField(max_length=255),
        ),
    ]
