# Generated by Django 5.0.3 on 2024-03-14 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0004_alter_item_seller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='created_ad',
        ),
        migrations.RemoveField(
            model_name='item',
            name='created_by',
        ),
    ]
